-- Active: 1684760132486@@127.0.0.1@5432@multiapp
DROP SCHEMA IF EXISTS users_schema CASCADE;

CREATE SCHEMA IF NOT EXISTS users_schema;

DROP SCHEMA IF EXISTS products_schema CASCADE;
CREATE SCHEMA IF NOT EXISTS products_schema;

DROP SCHEMA IF EXISTS forum_schema CASCADE;
CREATE SCHEMA IF NOT EXISTS forum_schema;

DROP SCHEMA IF EXISTS gallery_schema CASCADE;
CREATE SCHEMA IF NOT EXISTS gallery_schema;